### ISSUE TITLE
Does not seem to work with other SPI devices

### ISSUE THREAD

**Issue by cranefist** [RCmags/ADNS3080#1]
I have this set up with a OLED display, using adafruit library... and if the OLED is initialized, the sensor just spews out noise.

**Comment by RCmags** [comment]
Were you able to get the sensor to work, without the display connected? Do the examples output reasonable data? 

I know this library works for two adns3080s running at the same time, yet assigned different CS pins.

**Comment by cranefist** [comment]
Yes, it did work on its own. But when i have the display connected with a different CS pin its just spews random data.

**Comment by RCmags** [comment]
Thanks for the update! 
Please tell me the model of the screen you used, and whatever library you used to interface with it. I would like to replicate this problem.
