### ISSUE TITLE
Displacement always [0,0]

### ISSUE THREAD

**Issue by NiklasLeukroth** [RCmags/ADNS3080#3]
Hey, I tried your library and the example "displacement.ino" sketch compiles and can be uploaded, but the output of the setup for me is always [0,0]. I have also tried this with 2 sensors, so I am guessing I might be doing something incorrect, rather than both sensors being broken. 
The setup is faithfully recreated to your image however, so I fail to see where I might make a mistake. Do you have any initial idea what could be the issue?

Kind regards,

Niklas

**Comment by RCmags** [comment]
Have you removed the sticker that covers the sensor? you need to unscrew the lens to see it.

Is the lens focused? Use the [frame capture](https://github.com/RCmags/ADNS3080_frame_capture) script to adjust the focal length until you get a clear image.

**Comment by NiklasLeukroth** [comment]
Yes, the sticker is removed and I have gotten further in figuring out where the issue stems from. It appears the sensor is not properly recognized. Essentially the sensor.setup() does not succeed. Analyzing this further using the mentioned repos by Neumi and Lauszus in the description, it appears that reading the sensor id appears to be 0x00 at all times. One of the checks they perform is the following:
`uint8_t id = spiRead(ADNS3080_PRODUCT_ID);
  if (id == ADNS3080_PRODUCT_ID_VALUE)
    Serial.println(F("ADNS-3080 found"));`

The id never matches with the `ADNS3080_PRODUCT_ID_VALUE` and is in fact 0x00, but I do not yet know why this is happening with my sensors.

**Comment by RCmags** [comment]
Try checking the connection of the MOSI, MISO, SCL, and NCS pins. The unchanging id may indicate a faulty connection. Alternatively, if you have an oscilloscope, try measuring the output pins to see if there is any output. 

Please note that the library was written for one of these [modules](https://static.optimusdigital.ro/8577-thickbox_default/adns-3080-optical-flow-sensor-module.jpg), if yours differs, then perhaps the sensor uses a different communication registers. I recall there being variants of the ADNS-3080 with different serial numbers.
